'use strict';
// Synthetic concept data. No provider, wallet or model calls occur in this UI.
const contract='0x0000000000000000000000000000000000000002';
const wallets=[{name:'Sunday wallet',value:8624.2,share:69.1},{name:'Little vault',value:3856.12,share:30.9}];
const assets=[
 {symbol:'ETH',name:'Ether',network:'Base',chain:8453,value:7320.32,quantity:'2.4',price:3050.13333,protocol:'Native',id:'native'},
 {symbol:'MT',name:'Demo Moon Token',network:'Base',chain:8453,value:3240,quantity:'10,800',price:.3,protocol:'Mint Club',id:contract},
 {symbol:'USDC',name:'Demo USD Coin',network:'Ethereum',chain:1,value:1920,quantity:'1,920',price:1,protocol:'Uniswap',id:'0x0000000000000000000000000000000000000003'},
 {symbol:'DUST',name:'Demo small position',network:'Blast',chain:81457,value:7.6,quantity:'76',price:.1,protocol:'Mint Club',id:'0x0000000000000000000000000000000000000004'},
 {symbol:'LIL',name:'Demo little position',network:'Base',chain:8453,value:3,quantity:'30',price:.1,protocol:'Mint Club',id:'0x0000000000000000000000000000000000000005'},
 {symbol:'MIST',name:'Demo unpriced token',network:'Blast',chain:81457,value:null,quantity:'240',price:null,protocol:'Mint Club',id:'0x0000000000000000000000000000000000000006'}
];
function positionsForWallet(index){return index===0?assets.filter(a=>a.network==='Base').map(a=>a.symbol==='MT'?{...a,value:2100,quantity:'7,000'}:a):[...assets.filter(a=>a.network!=='Base'),{...assets.find(a=>a.symbol==='MT'),value:1140,quantity:'3,800'}];}
wallets.forEach((w,i)=>{w.value=positionsForWallet(i).reduce((s,a)=>s+(a.value||0),0);w.share=(100*w.value/assets.reduce((s,a)=>s+(a.value||0),0)).toFixed(1);});
const concepts=[{id:'chic',name:'Kira · Chic Researcher',description:'An adult webtoon researcher, calm eyes and a lavender notebook.',image:'kira-chic.png'},
 {id:'webtoon',name:'Moon Researcher',description:'Webtoon lines, expressive eyes, a small notebook.',image:'kira-webtoon.png'},
 {id:'star',name:'Star Scout',description:'A simple star silhouette with a research satchel.',image:'kira-star.png'},
 {id:'cloud',name:'Cloud Archivist',description:'A soft cloud with a quiet, attentive presence.',image:'kira-cloud.png'},
 {id:'moon',name:'Moon Librarian · 3D',description:'The earlier clay concept, kept for comparison.',image:'kira-moon.png'}];
let selected='chic',threshold=10,search='',job='partial',explain=false;
const $=s=>document.querySelector(s),money=n=>n===null?'Unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const portrait=()=>`<img class="assistant-art ${selected==='webtoon'?'webtoon-portrait':''}" src="assets/${concepts.find(c=>c.id===selected).image}" alt="Kira, your research companion">`;
const logo=chain=>`<img class="chain-logo" src="https://mint.club/assets/networks/${chain===8453?'base.svg':chain===1?'ethereum@2x.png':'blast@2x.png'}" alt="">`;
const protocol=a=>a.protocol==='Native'?'Native':`<a class="protocol" href="${a.protocol==='Mint Club'?'https://mint.club/explore':'https://app.uniswap.org/'}" target="_blank" rel="noopener noreferrer" title="Demo link opens the protocol website">${a.protocol} ↗</a>`;
function rows(list){return list.map(a=>`<tr><td><a class="asset-cell" href="#/token/${a.chain}/${a.id}"><span class="token-icon">${escape(a.symbol.slice(0,2))}</span><span><strong>${escape(a.symbol)}</strong><small>${escape(a.name)}</small></span></a></td><td><a href="#/network/${a.chain}">${escape(a.network)}</a></td><td class="protocol-col">${protocol(a)}</td><td class="numeric">${money(a.value)}</td></tr>`).join('');}
function table(list){return `<div class="table-wrap"><table><thead><tr><th>ASSET</th><th>NETWORK</th><th class="protocol-col">SOURCE</th><th class="numeric">KNOWN VALUE</th></tr></thead><tbody>${rows(list)}</tbody></table>${list.length?'':'<p class="empty">No sample positions match these filters.</p>'}</div>`;}
function toolbar(){return `<div class="toolbar"><div class="filters" aria-label="Minimum position value">${[0,5,10].map(n=>`<button data-filter="${n}" aria-pressed="${threshold===n}">${n?'≥ $'+n:'All positions'}</button>`).join('')}</div><input id="search" type="search" aria-label="Search sample assets" placeholder="Search assets" value="${escape(search)}"></div>`;}
function filtered(list){return list.filter(a=>(!threshold||a.value!==null&&a.value>=threshold)&&`${a.symbol} ${a.name} ${a.id}`.toLowerCase().includes(search.toLowerCase()));}
function heading(title,subtitle,button=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${subtitle}</p></div>${button}</div>`;}
function totalExplanation(){return `<div class="notice explanation ${explain?'visible':''}">Known value sums priced direct positions only. Unpriced tokens, pool liquidity, shared curve reserves and testnets are excluded. All figures here are synthetic.</div>`;}
function home(){return heading('A little clarity, together.','Your wallets, with the details gently untangled.',`<button class="primary" data-preview>Preview analysis</button>`)+
 `<section class="hero"><div class="eyebrow">YOUR KNOWN PORTFOLIO VALUE</div><div class="figure">$12,490.92</div><p>Across two sample wallets. One token still needs a reliable price.</p><button class="inline-link" data-explain>What goes into this total? ↗</button><img src="assets/${concepts.find(c=>c.id===selected).image}" alt=""><small>Synthetic snapshot · Updated Oct 3, 2026</small></section>`+totalExplanation()+
 `<div class="stats"><div class="stat"><strong>2</strong><span>Wallets together</span></div><div class="stat"><strong>3</strong><span>Networks explored</span></div><div class="stat"><strong>1</strong><span>Unpriced position</span></div></div>`+
 `<section class="section"><div class="section-top"><h2>Your little collection</h2><span class="muted">2 wallets</span></div><div class="cards">${wallets.map((w,i)=>`<a class="card" href="#/wallet/${i}"><div class="card-row"><div class="asset-cell"><span class="wallet-icon">${i?'✧':'◈'}</span><strong>${w.name}</strong></div><span class="badge">${i?'Partial':'Checked'}</span></div><span class="value">${money(w.value)}</span><small>Sample holdings · ${w.share}% of priced sample positions</small></a>`).join('')}</div></section>`+
 `<section class="section"><h2>Across your networks</h2><div class="network-pills">${[[8453,'Base'],[1,'Ethereum'],[81457,'Blast']].map(([c,n])=>`<a href="#/network/${c}">${logo(c)}${n} ↗</a>`).join('')}</div></section>`+
 `<section class="section"><div class="section-top"><h2>Held with a market reference</h2><span class="muted">Sample data</span></div>${toolbar()}<div id="holdings">${table(filtered(assets))}</div></section>`;}
function tokenPage(chain,id){const a=assets.find(a=>a.chain===Number(chain)&&a.id===id);if(!a)return heading('No sample token found','This concept contains synthetic assets only.');
 return heading(a.name,`${a.network} · ${a.protocol} · Sample token identity`)+`<section class="detail-card"><div class="eyebrow">COMBINED KNOWN VALUE</div><div class="detail-total">${money(a.value)}</div><p class="muted">${a.quantity} ${a.symbol} across ${a.symbol==='MT'?'2':'1'} sample wallet${a.symbol==='MT'?'s':''}.</p><dl class="definition"><div><dt>Recorded unit price</dt><dd>${money(a.price)}</dd></div><div><dt>Price basis</dt><dd>${a.protocol==='Mint Club'?'Curve spot estimate':'Sample market reference'}</dd></div><div><dt>Identity</dt><dd>${a.chain} · ${a.id}</dd></div><div><dt>Observed</dt><dd>Oct 3, 2026 · Synthetic</dd></div></dl></section><div class="notice">This sample value is an estimate. Curve backing is shared and is excluded from wallet totals.</div><section class="section"><h2>Where it is held</h2><div class="table-wrap"><table><thead><tr><th>WALLET</th><th class="numeric">BALANCE</th><th class="numeric">VALUE</th></tr></thead><tbody><tr><td><a href="#/wallet/${a.network==='Base'?0:1}">${a.network==='Base'?'Sunday wallet':'Little vault'}</a></td><td class="numeric">${a.symbol==='MT'?'7,000':a.quantity} ${a.symbol}</td><td class="numeric">${money(a.symbol==='MT'?2100:a.value)}</td></tr>${a.symbol==='MT'?'<tr><td><a href="#/wallet/1">Little vault</a></td><td class="numeric">3,800 MT</td><td class="numeric">$1,140.00</td></tr>':''}</tbody></table></div></section><section class="section"><h2>Research sources</h2><p>${protocol(a)}</p><p class="muted">Demo links open the protocol website. Production links use the recorded chain and contract.</p></section>`;}
function networkPage(chain){const list=assets.filter(a=>a.chain===Number(chain)),name=list[0]?.network||'Unknown network';return heading(name,'Combined sample positions across registered demo wallets')+`<section class="detail-card"><div class="eyebrow">KNOWN NETWORK VALUE</div><div class="detail-total">${money(list.reduce((s,a)=>s+(a.value||0),0))}</div><p class="muted">${list.length} positions · ${list.filter(a=>a.value===null).length} unpriced</p></section>${toolbar()}<div id="holdings">${table(filtered(list))}</div>`;}
function walletPage(index){const w=wallets[Number(index)];if(!w)return heading('Wallet not found','Use a sample wallet from the sidebar.');const list=positionsForWallet(Number(index));return heading(w.name,'Synthetic identity · Read-only sample portfolio')+`<section class="detail-card"><div class="eyebrow">SAMPLE WALLET VALUE</div><div class="detail-total">${money(list.reduce((s,a)=>s+(a.value||0),0))}</div><p class="muted">Demo positions only. No real address is connected.</p></section>${toolbar()}<div id="holdings">${table(filtered(list))}</div>`;}
function activity(){const stages=['Queued','Discovering held assets','Checking on-chain balances','Pricing and coverage'];const stage=job==='queued'?0:job==='checking'?2:4;return heading('A notebook in progress.','Inspect the research journey, one stage at a time.')+`<div class="notice">SIMULATED JOB · These controls preview states. They do not start an analysis or contact any provider.</div><div class="state-choices" aria-label="Preview job state">${[['queued','Queued'],['checking','Checking'],['partial','Partial result']].map(([key,label])=>`<button data-job="${key}" class="${key===job?'active':''}" aria-pressed="${key===job}">${label}</button>`).join('')}</div><section class="detail-card section"><div class="card-row"><h2>Sample analysis</h2><span class="badge">${job==='partial'?'Completed with gaps':job==='queued'?'Queued':'Checking balances'}</span></div><ol class="timeline">${stages.map((s,i)=>`<li class="${i<stage?'done':''}"><strong>${s}</strong><small>${i<stage?'Simulated stage recorded':i===stage?'Simulated current stage':'Not started in this preview'}</small></li>`).join('')}</ol>${job==='partial'?'<p>I kept the priced positions. Blast still has one token without a reliable price.</p><a class="inline-link" href="#/home">View sample results →</a>':'<p class="muted">A real job will show recorded progress and block references here.</p>'}</section>`;}
function characters(){return heading('Meet the face of Kira.','Original concepts. Your selection changes this demo only.')+`<div class="character-grid">${concepts.map(c=>`<article class="card"><img src="assets/${c.image}" alt="${c.name} character concept"><div><h3>${c.name}</h3><p>${c.description}</p><button data-character="${c.id}" aria-pressed="${selected===c.id}" class="${selected===c.id?'primary':''}">${selected===c.id?'In this preview':'Try this Kira'}</button></div></article>`).join('')}</div><div class="notice">The adult webtoon researcher reflects the latest request. Earlier 3D concepts remain available for comparison. Final production artwork and expression sets are still a separate milestone.</div>`;}
function assistantContent(route){let note=route.startsWith('token')?'This token has its own chain and contract identity. Its curve reserve belongs to the whole curve, so I do not add it once per wallet.':route.startsWith('activity')?'A partial result is still useful. I keep what was verified and tell you what needs another look.':'I gathered your sample wallets in one place. The total includes priced positions; one token still needs a reliable price.';return `<div class="assistant-title"><span>With Kira ✦</span><span>CONCEPT</span></div>${portrait()}<div class="note"><h3>Let's make it clear.</h3><p>${note}</p><p class="signature">A small note from Kira</p></div><div class="note-actions"><button data-explain>Why is this the known total?</button><button data-preview>Show an analysis journey</button></div><div class="assistant-foot">Chat preview<input disabled aria-label="Agent chat is not connected in this prototype" placeholder="Not connected in this prototype"><span>Your data stays out of this concept demo.</span></div>`;}
function render(){const route=location.hash.slice(2)||'home',parts=route.split('/');let content=parts[0]==='home'?home():parts[0]==='wallet'?walletPage(parts[1]):parts[0]==='token'?tokenPage(parts[1],parts[2]):parts[0]==='network'?networkPage(parts[1]):parts[0]==='activity'?activity():parts[0]==='characters'?characters():`<section class="assistant-page">${heading("Kira's notes",'An explanation, without hiding the evidence.')}${assistantContent(route)}${totalExplanation()}</section>`;$('#content').innerHTML=content;$('#assistant').innerHTML=assistantContent(route);const trail=parts[0]==='home'?'Home':parts[0]==='token'?`<a href="#/network/${parts[1]}">${assets.find(a=>a.chain===Number(parts[1]))?.network||'Network'}</a><span>/</span><span>${assets.find(a=>a.chain===Number(parts[1])&&a.id===parts[2])?.symbol||'Token'}</span>`:parts[0]==='wallet'?wallets[Number(parts[1])]?.name||'Wallet':parts[0]==='network'?assets.find(a=>a.chain===Number(parts[1]))?.network||'Network':parts[0]==='characters'?'Meet Kira':parts[0]==='activity'?'Research activity':"Kira's notes";$('#breadcrumb').innerHTML=parts[0]==='home'?'<span>Home</span>':`<a href="#/home">Home</a><span>/</span>${trail}`;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===route));}
document.addEventListener('click',e=>{const target=e.target.closest('button');if(!target)return;if(target.dataset.filter!==undefined){threshold=Number(target.dataset.filter);render();}else if(target.dataset.character){selected=target.dataset.character;render();$('#announcement').textContent='Character preview changed.';}else if(target.dataset.job){job=target.dataset.job;render();$('#announcement').textContent='Simulated job state: '+job;}else if(target.hasAttribute('data-preview')){location.hash='/activity';}else if(target.hasAttribute('data-explain')){explain=!explain;if(!['home','assistant'].includes(location.hash.slice(2))){location.hash='/assistant';}else render();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const route=location.hash.slice(2)||'home',p=route.split('/');const list=p[0]==='network'?assets.filter(a=>a.chain===Number(p[1])):p[0]==='wallet'?positionsForWallet(Number(p[1])):assets;$('#holdings').innerHTML=table(filtered(list));}});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();$('#content').focus();$('#content').scrollIntoView({block:'start'});});
window.addEventListener('hashchange',()=>{search='';render();});render();
